---
title: "MATH 264: Bayesian Project"
output: html_notebook
---

### Sampling Distribution: Poisson  

$$p(y ~|~ \alpha) = \frac{1}{y!}(\alpha t)^{y}e^{-(\alpha t)}$$

#### Assumptions:

* $\theta$ the number of times an event occurs in an interval and it can take values 0, 1, 2,...
    - Confirmed
* The occurrence of one event does not affect the probability that a second event will occur. That is, events occur independently.
    - LIKELY VIOLATED: if someone gets shot and killed, it is likely (increased probability) that someone else will also die soon either by association or as a result of retaliation.
* The rate at which events occur is constant. The rate cannot be higher in some intervals and lower in other intervals.
    - LIKELY VIOLATED: fight scenes, beginning/end less likely to have deaths than the middle/climax]
* Two events cannot occur at exactly the same instant.
    - Technically two people 
* The probability of an event in an interval is proportional to the length of the interval.
    - Seems reasonable: longer movies allow more time for more deaths
    
    
### Conjugate Prior: Gamma

$$p(\alpha ~|~ a, b) = \frac{b^a}{\Gamma(a)}\alpha^{a-1}e^{-b\alpha}$$

```{r, echo = FALSE}
## Death count data (Quentin Taratino movies removed)
dc <- read.csv("filmdeathcounts_no-qt.csv", 
               header = TRUE, 
               stringsAsFactors = FALSE)

## Project dataset meta data
qt <- read.table("qt_meta.txt", 
                 header = FALSE, 
                 col.names = c("movie", "rating", "duration", "year", "genre"),
                 sep = ";",
                 strip.white = TRUE,
                 stringsAsFactors = FALSE)

## Genre list for project dataset
qt.g <- unique(unlist(strsplit(paste(qt$genre, collapse = ", ", sep = ""), ", ")))

## Splitting genre list for each movie in death count dataset
dc.g <- strsplit(tolower(dc$Genre), "|", fixed = TRUE)

## Checking if any genres match those of project genre list
dc$Genre_Match <- logical(1)
for (i in seq_along(dc.g)) {
  dc$Genre_Match[i] <- any(dc.g[[i]] %in% qt.g)
}

## Filter death count dataset
## 1) Rating R or Not Rates
## 2) Year later than 1991 (earliest is 1992)
## 3) Genre Match
dc.filt <- dc[dc$MPAA_Rating %in% c("R", "Unrated", "NR") & dc$Year > 1991 & dc$Genre_Match == TRUE, ]
rownames(dc.filt) <- 1:nrow(dc.filt)

h <- 10
k <- 1.5
theta <- 35.5

d <- density(dc.filt$Body_Count, kernel = "epanechnikov", bw = h, from = 0)
plot(d, ann = FALSE, axes = FALSE,
     xlim = c(-100, 700), ylim = c(0, 0.02), 
     bty = "n", col = "violetred", lwd = 1.5)
axis(1, at = seq.int(-50, 700, 50), labels = NA)
axis(1, at = seq.int(0, 600, 100), lwd = 0, lwd.ticks = 0)
axis(2, at = seq.int(0, 0.02, 0.005), pos = -75)
    
## Gamma parameter controls
g.mean <- k*theta
g.mode <- (k-1)*theta
g.var <- k*(theta)^2

## Plot theoretical gamma distribution
curve(dgamma(x, shape = k, scale = theta), from = 0, to = 600, add = TRUE, lty = 2, col = "slateblue")
#legend("top", legend = paste(c("Mean =", "Mode =", "Variance ="), c(g.mean, g.mode, g.var)), bty = "n")
legend("top", legend = c("KDE", "Gamma"), col = c("slateblue", "violetred"), lty = c(2,1), bty = "n")
title(xlab = expression(theta), ylab = "Density")
```


